server:
  port: 8383

turbine:
  appConfig: author,credentials
  aggregator:
    clusterConfig: AUTHOR,CREDENTIALS

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    region: default
    registryFetchIntervalSeconds : 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

